name: 'paruvendu_project'
version: '1.0.0'
profile: 'paru_vendu'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  paruvendu_project:
    staging:
      +materialized: view
    marts:
      +materialized: table
