version: 2

sources:
  - name: paruvendu_history_source   # alias dbt (libre)
    description: >
      Historique des annonces immobilières ParuVendu.
      Données historisées hebdomadairement par PySpark
      à partir des snapshots Gold.

    schema: paruvendu_athena          # Database Athena 

    tables:
      - name: paruvendu_history       # Nom de la table Athena
        description: >
          Table Athena pointant vers l’historique des annonces
          stocké sur S3 (history/history.parquet).
        
        loaded_at_field: >
          CAST(
            date_add(
              'day',
              CAST(date_scraping AS INTEGER),
              DATE '1970-01-01'
            ) AS TIMESTAMP
          )

        freshness:
          warn_after:
            count: 48
            period: hour
          error_after:
            count: 96
            period: hour

        columns:
          - name: id_annonce
            description: Identifiant de l’annonce
            tests:
              - not_null

          - name: date_scraping
            description: Date d’extraction de l’annonce
            tests:
              - not_null
